### PR TITLE
38 integrate palmyra with google drive api

### LINKED ISSUE #38: Integrate Palmyra with Google Drive API
**Problem**
User progress is lost when browser is refreshed

**Solution**
Use Google Drive API as the storage for users' files

**Alternatives**
We can create our backend with services like Google Drive, but it will take a lot of work and it is less secure

**References**
[Google Drive API](https://developers.google.com/drive/api/guides/about-sdk)

### PR DESCRIPTION
**Pull request by vulongphan**
This PR implements the following
- Allow uploading files to Google Drive (new files are created and existing files are updated)
- Enforce persistence for Google authentication (users do not have to authenticate the second time in the same session)
- Enable Google Drive file picker pop-up for retrieving uploaded files

### CODE REVIEW

**Review by muhammed-abuodeh — COMMENTED** [review]
(commit [73b4f52](https://github.com/CAMeL-Lab/palmyra/pull/39/commits/73b4f52ad1c33d967ddc7c11e0a0b0519fbb9c50)) is it fine for the GCP_CLIENT_ID and GCP_API_KEY to be public (just making sure)?

**Review by muhammed-abuodeh — COMMENTED** [review]
change #saveremote to #saveRemote

**Review by muhammed-abuodeh — COMMENTED** [review]
saveremoteToggle() -> saveRemoteToggle
make sure naming is consistent

**Comment by vulongphan** [comment]
> (commit [73b4f52](https://github.com/CAMeL-Lab/palmyra/pull/39/commits/73b4f52ad1c33d967ddc7c11e0a0b0519fbb9c50)) is it fine for the GCP_CLIENT_ID and GCP_API_KEY to be public (just making sure)?

Yes, I think this is not the best practice. A workaround would be to set environment variables in Github Page; and since I do not have access to the repo settings, we would need to work together on this

**Pull request closed without merging**
