### PR TITLE
29 implement undo redo feature

### PR DESCRIPTION
**Pull request by vulongphan**
This PR implements undo-redo feature and add corresponding unit tests

### CODE REVIEW

**Comment by vulongphan** [comment]
Link to #29 #33 #15

**Comment by muhammed-abuodeh** [comment]
If you drag a node and release it, it'll be floating.

**Comment by vulongphan** [comment]
I cannot reproduce the bug on this branch. Did you pull the most up-to-date version of it?

**Comment by muhammed-abuodeh** [comment]
> I cannot reproduce the bug on this branch. Did you pull the most up-to-date version of it?
Got it working, thanks!

There is another bug I spotted. Do the following to reproduce:
collapse node
move node 4 times
undo 3 times
expand node

**Comment by muhammed-abuodeh** [comment]
Issue with d3 functionality, not the new feature.

**Pull request merged**
